@startuml
'https://plantuml.com/class-diagram

class Juego {
    - partidaActual
    - partidasGuardadas

    + cargarPartida()
    + jugar()
}

class Partida {
    - jugadorUno
    - jugadorDos
    - mapa
    - turno

    + asignarNombre(Jugador)
    + asignarColor(Jugador)
    + asignarRaza(Jugador)
    + jugar()
    + . . .  ()
}

class Jugador {
    - nombre
    - color
    - raza


    + contruir()
    + atacar()
    + recolectar()
    + evolucionar()
}

abstract class Raza {
    - unidades
    - construcciones
    - bandoDeRecursos

    + agregarConstruccion()
    + recolectar()
    + evolucionar()
}

class Zerg {
    + agregarConstruccion()
    + recolectar()
    + evolucionar()
}

class Protoss {
    + agregarConstruccion()
    + recolectar()
    + evolucionar()
}

abstract class Unidad {
    - vida
    - ...

    + atacar()
}

class UnidadZerg {}

class UnidadProtoss {}


interface Construccion {
    +{abstract}construir():void
    +{abstract}avanzarTurno():void

}

interface Refineria {
    + {abstract}recolectar()
}
interface Refineria
note left : Pueden llegar a haber 2 tipos de refinerias (Gas y Mineral)


interface ConstruccionConRadio {
    +{abstract}ampliarRadio()
}

interface ConstruccionNormal {

    +{abstract}evolucionar()
    }

class Extractor {
    - tiempoConstruccion
    - vida
    +recolectar()
    +construir()
}

class Asimilador {
    - tiempoConstruccion
    - vida
    +recolectar()
    +construir()
    - escudo
}

class NexoMineral {
    - tiempoConstruccion
    - vida
    +recolectar()
    +construir()
    - escudo
}

class Criadero {
    - tiempoConstruccion
    - vida
     +evolucionar()
     +construir()
     +ampliarRadio()
}

class Pilon {
    - tiempoConstruccion
    - vida
    +ampliarRadio()
    +construir()
    - escudo
}

class Espiral {
    - tiempoConstruccion
    - vida
    +evolucionar()
    +construir()

}

class ReservaProduccion {
    - tiempoConstruccion
    - vida
     +evolucionar()
     +construir()
}

class Guarida {
    - tiempoConstruccion
    - vida
    +evolucionar()
    +construir()

}

class PuertoEscalar {
    - tiempoConstruccion
    - vida
    +evolucionar()
    +construir()
    - escudo

}

class Acceso {
    - tiempoConstruccion
    - vida
     +evolucionar()
     +construir()
    - escudo
}

class Mapa {
    - mapa: [][]

    + agregarUnidad()
    + agregarConstruccion()
}

abstract class Casilla {
    - unidad
    - terreno
    - construccion

    + agregarUnidad()
    + agregarConstruccion()
    + setTerrreno()
}

class Vacia {
    + agregarUnidad()
    + agregarConstruccion()
    + setTerreno()
}

class ConRecurso {
    - recurso

    + agregarUnidad()
    + agregarConstruccion()
    + setTerreno()
}

interface Terreno {
    + agregarConstruccion()
}

class Terreno
note left: Se aplica patrón Strategy

class ConMoho {
    + agregarConstruccion()
}

class ConEnergia {
    + agregarConstruccion()
}

class SinNada {
    + agregarConstruccion()
}

abstract class Recurso {
    - cantidad
    + recolectar()
}

class Volcan {
    + recolectar()
}

class NodoMineral {
    + recolectar()
}

class Turno {

   +avanzarTurno(Jugador)
   +jugar(Jugador)

   }



Juego *--> Partida
Partida "2" *-> Jugador
Mapa <-* Partida
Partida *--> Turno

Jugador *-> Raza
Raza <|-up- Zerg
Raza <|-up- Protoss
Raza -> Unidad
Unidad <|-right- UnidadZerg
Unidad <|-up- UnidadProtoss

Raza-->Construccion



Construccion <|.. Refineria
Construccion <|.. ConstruccionConRadio
Construccion <|.. ConstruccionNormal



Refineria <|.. Extractor
Refineria <|.. Asimilador
Refineria <|.. NexoMineral




ConstruccionConRadio <|.. Criadero
ConstruccionConRadio <|.. Pilon





ConstruccionNormal <|.. Criadero
ConstruccionNormal <|.. Espiral
ConstruccionNormal <|.. ReservaProduccion
ConstruccionNormal <|.. Guarida
ConstruccionNormal <|.. PuertoEscalar
ConstruccionNormal <|.. Acceso

Casilla "*" <-* Mapa
Terreno <-* Casilla
Casilla <|-- Vacia
Casilla <|-- ConRecurso
Terreno <|.. ConMoho
Terreno <|... ConEnergia
Terreno <|.. SinNada

ConRecurso --> Recurso
Recurso <|-- Volcan
Recurso <|-- NodoMineral




@enduml