@startuml
'https://plantuml.com/class-diagram

class Partida {
    - jugadorUno
    - jugadorDos
    - mapa

    + asignarNombre(Jugador)
    + asignarColor(Jugador)
    + asignarRaza(Jugador)
    + jugar()
}

class Jugador {
    - nombre
    - color

    + elegirAccion(mapa)
    + ejecutarAccion()
    + jugar(mapa)
}

abstract class Raza {
    - bancoDeRecursos
    - capacidadSuministro
    - accion

    + comprar(construccion)
    + comprar(unidad)
    + elegirAccion(turno, mapa)
    + ejecutarAccion()
    + asignarAccion(accion)
}

class Zerg {
    - acciones
    + elegirAccion(turno, mapa)
}

class Protoss {
    - acciones
    + elegirAccion(turno, mapa)
}

abstract class Construccion {
    - vida
    - tiempoConstruccion
    - costos
    + construir()
    + esPosibleConstruirEn()
}

abstract class ConstruccionZerg {
    + construir()
    + esPosibleConstruirEn()
}

abstract class ConstruccionProtoss {
    - escudo
    + construir()
    + esPosibleConstruirEn()
}

class Mapa {
    - mapa[][] : Casillas

    + buscar(Coordenada) : Casilla
}

class Casilla {

    - construccion
    - unidad

    + agregarUnidad()
    + agregarConstruccion()
    + setTerrreno()
    + setRecurso()
}

class Coordenada {
    - fila
    - columna

    +esIgual(Coordenada)
    +tieneMismaFilaColumna()
}

class SinRecurso {
    + esPosibleConstruir(construccion)
}

interface Terreno {
    + esPosibleConstruir(construccion)
}

class ConMoho {
    + esPosibleConstruir(construccion)
}

class ConEnergia {
    + esPosibleConstruir(construccion)
}

class SinTerreno {
    + esPosibleConstruir(construccion)
}

class Volcan {
    - cantidad
    + recolectar() : int
    + esPosibleConstruir(construccion)
}

class NodoMineral {
    - cantidad
    + recolectar() : int
    + esPosibleConstruir(construccion)
}

class Turno {
    - estaJugando : bool
    +sigueJugando()
    +dejarDeJugar()
    +jugar()

}

interface Recurso {
    + esPosibleConstruir(construccion)
}


Partida "2" *- Jugador
Mapa -o Partida
Jugador o-up- Turno

Jugador *- Raza
Raza <|-- Zerg
Raza <|-- Protoss

Zerg --> ConstruccionZerg
Protoss --> ConstruccionProtoss
ConstruccionProtoss --|> Construccion
ConstruccionZerg --|> Construccion

Casilla "*" -* Mapa
Terreno -* Casilla
Coordenada --o Casilla
Casilla *-- Recurso

Recurso <|.. Volcan
Recurso <|.. NodoMineral
Recurso <|.. SinRecurso

ConMoho ..|> Terreno
Terreno <|.. ConEnergia
SinTerreno .|> Terreno

interface Area{
 +esPosibleAgregar(unidad)
}
class AreaTerrestre{
+esPosibleAgregar(unidad)
}
class AreaEspacial{
+esPosibleAgregar(unidad)
}

Casilla *-- Area
Area <|.. AreaTerrestre
Area <|.. AreaEspacial



@enduml