@startuml
'https://plantuml.com/class-diagram

class Casilla {
    - construible

    + agregarUnidad()
    + agregarConstruccion()
    + setTerrreno()
    + setRecurso()
}

interface Construible {
    asignarConstruccion(construccion)
}

class HayConstruccion {
    asignarConstruccion(construccion)
}

class NoHayConstruccion {
    asignarConstruccion()
}

interface Terreno {
    asignarConstruccion()
}

class ConMoho {
    -recurso
    +asignarConstruccion(construccionZerg)
}

class ConEnergia {
    -recurso
    +asignarConstruccion(construccionProtoss)
}

class Vacio {
    -recurso
    +asignarConstruccion()
}

interface Recurso {
    +asignarConstruccion()
}

class Volcan {
    -construccion
    +asignarConstruccion(refineria : DeGas)
}

class NodoMineral {
    -construccion
    +asignarConstruccion(refineria : DeMineral)
}

class SinRecurso {
    -construccion
    +asignarConstruccion(unaConstruccion)
}

Casilla -> Construible
Construible <|.. HayConstruccion
Construible <|.. NoHayConstruccion

Construible -> Terreno
Terreno <|.. ConEnergia
Terreno <|.. ConMoho
Terreno <|.. Vacio

Terreno -> Recurso
Recurso <|.. Volcan
Recurso <|.. NodoMineral
Recurso <|.. SinRecurso

@enduml