@startuml
'https://plantuml.com/class-diagram


abstract class Raza {
    - bancoDeRecursos
    - capacidadSuministro
    - acciones

    + comprar(construccion)
    + comprar(unidad)
}

class Zerg {
    + agregar(construccion)
    + agregar(unidad)
    + recolectar()
    + crearUnidad()
}

class Protoss {
    + agregar(construccion)
    + agregar(unidad)
    + recolectar()
    + crearUnidad()
}

interface AccionesProtoss {
    +crearUnidad()
    +crearConstruccion()
    +atacar(unidad)
    +atacar(construccion)
    +mover()
}

interface AccionesZerg {
    +crearUnidad()
    +crearConstruccion()
    +atacar(unidad)
    +atacar(construccion)
    +mover()
    evolucionarUnidad()
}

class Creacion {
    + crearConstruccion()
    + crearUnidad()
}

class Ataque {
    + atacar(unidad)
    + atacar(construccion)
}

class Movimiento {
    + mover()
}

class Evolucion {
    + evolucionarUnidad()
}

class Mapa {
    - mapa[][] : Casillas

    + buscar(Coordenada) : Casilla
}

Mapa <- Raza
Raza <|.. Zerg
Raza <|.. Protoss

Zerg --> AccionesZerg
Protoss --> AccionesProtoss
AccionesZerg <|.. Creacion
AccionesZerg <|.. Ataque
AccionesZerg <|.. Movimiento
AccionesZerg <|.. Evolucion

AccionesProtoss <|.. Creacion
AccionesProtoss <|.. Ataque
AccionesProtoss <|.. Movimiento




@enduml