@startuml
'https://plantuml.com/class-diagram


abstract class Raza {
    - bancoDeRecursos
    - capacidadSuministro
    - acciones

    + comprar(construccion)
    + comprar(unidad)
}

class Zerg {
    + agregar(construccion)
    + agregar(unidad)
    + recolectar()
    + crearUnidad()
}

class Protoss {
    - evolucion
    + agregar(construccion)
    + agregar(unidad)
    + recolectar()
    + crearUnidad()
}

interface Acciones {
    +ejecutar()
}

class Creacion {
    + crearConstruccion()
    + crearUnidad()
    + ejecutar()
}

class Ataque {
    + atacar(unidad)
    + atacar(construccion)
    + ejecutar()
}

class Movimiento {
    + mover()
    + ejecutar()
}

class EvolucionarUnidad {
    + evolucionarUnidad()
    + ejecutar()
}

class Mapa {
    - mapa[][] : Casillas

    + buscar(Coordenada) : Casilla
}

interface Evolucion {
    + ejecutar()
}

Mapa <- Raza
Raza <|.. Zerg
Raza <|.. Protoss

Zerg --> Acciones
Protoss --> Acciones
Acciones <|.. Creacion
Acciones <|.. Ataque
Acciones <|.. Movimiento

Zerg --> Evolucion
Evolucion <|.. EvolucionarUnidad




@enduml